### ISSUE TITLE
error in TouchSensor()

### ISSUE THREAD

**Issue by MKleinSB** [1010Technologies/pxt-makerbit#19]
I get an error when I use the function touchsensor.
Is it right that the program should display the number of the touched pin or even -1?
Well, I get an error when I try to compile it.

![error](https://user-images.githubusercontent.com/37311672/47587522-7b64e680-d963-11e8-8dbe-bbc0d690e901.png)

**Comment by philipphenkel** [comment]
Thanks for the report.
touch sensor ("Berührungssensor") ~~is~~ was intended for usage within the event notification functions. 

The compile error will be fixed with next release and "touch sensor" can be used everywhere. With next release, the touch sensor block will return the index of the last touched or released sensor.

**Comment by philipphenkel** [comment]
@MKleinSB Preview is available via "MakerBit": "github:1010technologies/pxt-makerbit#beta" in the project settings.
